/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Player(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/player.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-211.56, -190.06, -180.86]}>
          <mesh material={materials['08___Default']} geometry={nodes.mesh_0.geometry} />
          <mesh material={materials['02___Default']} geometry={nodes.mesh_1.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/player.glb')
